apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wordle
  region: us-west-2
  tags:
    project: udacity-capstone

iam:
  withOIDC: true

nodeGroups:
  - name: wordle-nodegroup
    instanceType: t2.small
    amiFamily: AmazonLinux2
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: udacity-capstone