apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle
  labels:
    app: wordle
    
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wordle
  template:
    metadata:
      labels:
        app: wordle
        
    spec:
      containers:
      - name: wordle
        image: kragavendra1100/wordle
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: wordle
  labels:
    app: wordle
    
spec:
  selector:
    app: wordle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer