apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordle
  labels:
    app: wordle
  namespace: default
spec:
  selector:
    matchLabels:
      app: wordle
  replicas: 2
  strategy:
    type: Create
  template:
    metadata:
      labels:
        app: wordle
    spec:
      containers:
      - name: wordle
        image: kragavendra1100/wordle:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wordle
  labels:
    name: wordle
spec:
  selector:
    app: wordle
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 80